Repository woowa-techcamp-2024/Team2-Dari, pull requests merged in 2024-08, with the labels that each got.

#6 feat#5/Spring Rest Docs 설정 및 테스트 api 추가
  build.gradle
  src/docs/asciidoc/api/test/hello.adoc
  src/docs/asciidoc/common/greet-status.adoc
  src/docs/asciidoc/docinfo.html
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/EnumType.java
  src/main/java/com/wootecam/festivals/TestController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/wootecam/festivals/FestivalsApplicationTests.java
  src/test/java/com/wootecam/festivals/docs/TestControllerTest.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocController.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocControllerTest.java
  src/test/java/com/wootecam/festivals/docs/utils/CustomResponseFieldsSnippet.java
  src/test/java/com/wootecam/festivals/docs/utils/DocumentLinkGenerator.java
  src/test/java/com/wootecam/festivals/docs/utils/EnumDocs.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsConfig.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
  src/test/resources/org/springframework/restdocs/templates/custom-response-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 설정

#8 config#4/Jacoco 룰 설정 및 Jacoco 관련 깃허브 액션 추가
  .github/pull_request_template.md
  .github/workflows/jacoco-rule.yml
  build.gradle
Labels: 기능

#12 fix#11/Spring REST Docs snippet style 깨지는 문제 수정
  .github/workflows/cr.yml
  .gitignore
  src/test/resources/org/springframework/restdocs/templates/custom-response-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 버그

#18 feat#3/config-querydsl
  .DS_Store
  .github/.DS_Store
  build.gradle
  src/.DS_Store
Labels: 설정

#26 feat#24/application.yml 작성 및 도커 컴포즈 구성
  .github/workflows/jacoco-rule.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 기능

#29 feat#23/유저 생성 기능 구현 및 설정 작성
  .github/workflows/jacoco-rule.yml
  build.gradle
  src/main/java/com/wootecam/festivals/domain/member/controller/MemberController.java
  src/main/java/com/wootecam/festivals/domain/member/dto/MemberCreateDto.java
  src/main/java/com/wootecam/festivals/domain/member/entity/Member.java
  src/main/java/com/wootecam/festivals/domain/member/repository/MemberRepository.java
  src/main/java/com/wootecam/festivals/domain/member/service/MemberService.java
  src/main/java/com/wootecam/festivals/global/audit/AuditingConfig.java
  src/main/java/com/wootecam/festivals/global/audit/BaseEntity.java
  src/main/resources/application.yml
  src/test/java/com/wootecam/festivals/domain/member/controller/MemberControllerTest.java
  src/test/java/com/wootecam/festivals/domain/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/festivals/utils/TestDBCleaner.java
Labels: 기능

#31 feat#17/create festival
  build.gradle
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestDto.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponseDto.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/exception/FestivalErrorCode.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/global/exception/ApiExceptionHandler.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestDtoTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponseDtoTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
Labels: 기능

#34 feat#30/Dockerfile 수정 및 prod 환경 설정
  .github/pull_request_template.md
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 기능

#32 feat#23/user revoke
  src/docs/asciidoc/api/domain/member/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/domain/member/controller/MemberController.java
  src/main/java/com/wootecam/festivals/domain/member/dto/MemberCreateRequestDto.java
  src/main/java/com/wootecam/festivals/domain/member/dto/MemberIdResponseDto.java
  src/main/java/com/wootecam/festivals/domain/member/entity/Member.java
  src/main/java/com/wootecam/festivals/domain/member/exception/UserErrorCode.java
  src/main/java/com/wootecam/festivals/domain/member/service/MemberService.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
  src/test/java/com/wootecam/festivals/domain/member/controller/MemberControllerTest.java
  src/test/java/com/wootecam/festivals/domain/member/service/MemberServiceTest.java
Labels: 기능

#36 chore/.DS_Store 삭제
  .DS_Store
  .github/.DS_Store
  src/.DS_Store
Labels: 기타

#41 feat#19/축제 상세 조회 구현
  src/docs/asciidoc/api/domain/festival/Festival.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponseDto.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalDetailResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/FestivalStatus.java
  src/main/java/com/wootecam/festivals/domain/festival/exception/FestivalErrorCode.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalFactory.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponseDtoTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponseTest.java
  src/test/java/com/wootecam/festivals/domain/festival/entity/FestivalTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
Labels: 기능

#40 feat#39/organization 전반적인 리팩토링
  src/docs/asciidoc/api/domain/organization/organization.adoc
  src/docs/asciidoc/api/test/hello.adoc
  src/docs/asciidoc/common/greet-status.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/wootecam/festivals/domain/organization/controller/OrganizationController.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationIdDto.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationIdResponse.java
  src/main/java/com/wootecam/festivals/domain/organization/entity/Organization.java
  src/main/java/com/wootecam/festivals/domain/organization/entity/OrganizationMember.java
  src/main/java/com/wootecam/festivals/domain/organization/service/OrganizationService.java
  src/main/java/com/wootecam/festivals/global/docs/TestController.java
  src/test/java/com/wootecam/festivals/docs/TestControllerTest.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocController.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocControllerTest.java
  src/test/java/com/wootecam/festivals/docs/utils/EnumDocs.java
  src/test/java/com/wootecam/festivals/domain/organization/controller/OrganizationControllerTest.java
  src/test/java/com/wootecam/festivals/domain/organization/dto/OrganizationCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/organization/service/OrganizationServiceTest.java
Labels: 리팩토링

#44 feat#38/Ticket 생성 기능 구현 및 테스트 환경 분리
  docker-compose.yml
  src/docs/asciidoc/api/domain/ticket/Ticket.adoc
  src/main/java/com/wootecam/festivals/domain/ticket/controller/TicketController.java
  src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketIdResponse.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketValidConstant.java
  src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketValidator.java
  src/main/resources/application.yml
  src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
  src/test/java/com/wootecam/festivals/domain/ticket/controller/TicketControllerTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/dto/TicketCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/utils/TicketValidatorTest.java
  src/test/resources/application.yml
Labels: 기능

#37 feat#22/로그인 로그아웃 로직 구현
  src/docs/asciidoc/api/domain/auth/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/domain/auth/controller/AuthController.java
  src/main/java/com/wootecam/festivals/domain/auth/dto/LoginRequest.java
  src/main/java/com/wootecam/festivals/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/wootecam/festivals/domain/auth/service/AuthService.java
  src/main/java/com/wootecam/festivals/domain/member/controller/MemberController.java
  src/main/java/com/wootecam/festivals/domain/organization/controller/OrganizationController.java
  src/main/java/com/wootecam/festivals/domain/organization/service/OrganizationService.java
  src/main/java/com/wootecam/festivals/global/auth/AuthArgumentResolver.java
  src/main/java/com/wootecam/festivals/global/auth/AuthUser.java
  src/main/java/com/wootecam/festivals/global/auth/Authentication.java
  src/main/java/com/wootecam/festivals/global/auth/AuthenticationContext.java
  src/main/java/com/wootecam/festivals/global/auth/SessionConfig.java
  src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  src/main/java/com/wootecam/festivals/global/interceptor/AuthInterceptor.java
  src/main/java/com/wootecam/festivals/global/utils/AuthenticationUtils.java
  src/main/java/com/wootecam/festivals/global/utils/SessionUtils.java
  src/test/java/com/wootecam/festivals/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/wootecam/festivals/domain/auth/dto/LoginRequestTest.java
  src/test/java/com/wootecam/festivals/domain/auth/service/AuthServiceTest.java
  src/test/java/com/wootecam/festivals/domain/member/controller/MemberControllerTest.java
  src/test/java/com/wootecam/festivals/domain/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/festivals/domain/organization/controller/OrganizationControllerTest.java
  src/test/java/com/wootecam/festivals/domain/organization/service/OrganizationServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/controller/TicketControllerTest.java
  src/test/java/com/wootecam/festivals/global/interceptor/AuthInterceptorTest.java
Labels: 기능

#50 config#49/QueryDSL 의존성 삭제
  build.gradle
Labels: 설정

#51 feat#48/Organization 삭제에 따른 코드 변경
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalDetailResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalFactory.java
  src/main/java/com/wootecam/festivals/domain/organization/controller/OrganizationController.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationIdResponse.java
  src/main/java/com/wootecam/festivals/domain/organization/dto/OrganizationResponse.java
  src/main/java/com/wootecam/festivals/domain/organization/entity/Organization.java
  src/main/java/com/wootecam/festivals/domain/organization/entity/OrganizationMember.java
  src/main/java/com/wootecam/festivals/domain/organization/entity/OrganizationRole.java
  src/main/java/com/wootecam/festivals/domain/organization/exception/OrganizationErrorCode.java
  src/main/java/com/wootecam/festivals/domain/organization/repository/OrganizationMemberRepository.java
  src/main/java/com/wootecam/festivals/domain/organization/repository/OrganizationRepository.java
  src/main/java/com/wootecam/festivals/domain/organization/service/OrganizationService.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocController.java
  src/test/java/com/wootecam/festivals/docs/utils/CommonDocControllerTest.java
  src/test/java/com/wootecam/festivals/docs/utils/EnumDocs.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/festival/entity/FestivalTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
  src/test/java/com/wootecam/festivals/domain/organization/controller/OrganizationControllerTest.java
  src/test/java/com/wootecam/festivals/domain/organization/dto/OrganizationCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/organization/entity/OrganizationTest.java
  src/test/java/com/wootecam/festivals/domain/organization/service/OrganizationServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/wootecam/festivals/utils/Fixture.java
Labels: 기능

#55 feat#45/Festival 리스트 페이지네이션 구현
  src/docs/asciidoc/api/domain/festival/Festival.adoc
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/Cursor.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalAdminResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalDetailResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalListResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/KeySetPageResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalFactory.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/festival/entity/FestivalTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
Labels: 기능

#57 ci#42/코드 리뷰 봇 프롬프트 수정
  .github/workflows/cr.yml
Labels: CI

#56 feat#43/티켓 구매
  src/docs/asciidoc/api/domain/organization/organization.adoc
  src/docs/asciidoc/api/domain/purchase/purchase.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchaseIdResponse.java
  src/main/java/com/wootecam/festivals/domain/purchase/entity/Purchase.java
  src/main/java/com/wootecam/festivals/domain/purchase/entity/PurchaseStatus.java
  src/main/java/com/wootecam/festivals/domain/purchase/exception/PurchaseErrorCode.java
  src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  src/main/java/com/wootecam/festivals/domain/ticket/exception/TicketErrorCode.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketFinder.java
  src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketStockTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/wootecam/festivals/utils/Fixture.java
Labels: 기능

#59 feat#53/ 동적 스케줄링을 통한 페스티벌 상태 변경 구현
  src/main/java/com/wootecam/festivals/FestivalsApplication.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerService.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalStatusUpdateService.java
  src/main/java/com/wootecam/festivals/global/config/SchedulerConfig.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalStatusUpdateServiceTest.java
Labels: 기능

#65 refactor#58 코드 컨벤션에 맞춘 리팩토링
  src/docs/asciidoc/api/domain/auth/auth.adoc
  src/docs/asciidoc/api/domain/festival/Festival.adoc
  src/docs/asciidoc/api/domain/member/member.adoc
  src/docs/asciidoc/api/domain/ticket/Ticket.adoc
  src/main/java/com/wootecam/festivals/FestivalsApplication.java
  src/main/java/com/wootecam/festivals/domain/auth/dto/LoginRequest.java
  src/main/java/com/wootecam/festivals/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalDetailResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalIdResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalListResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/FestivalProgressStatus.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/FestivalPublicationStatus.java
  src/main/java/com/wootecam/festivals/domain/festival/exception/FestivalErrorCode.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerService.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalStatusUpdateService.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalFactory.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalValidConstant.java
  src/main/java/com/wootecam/festivals/domain/festival/util/FestivalValidator.java
  src/main/java/com/wootecam/festivals/domain/member/controller/MemberController.java
  src/main/java/com/wootecam/festivals/domain/member/dto/MemberCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/member/dto/MemberResponse.java
  src/main/java/com/wootecam/festivals/domain/member/entity/Member.java
  src/main/java/com/wootecam/festivals/domain/member/exception/MemberErrorCode.java
  src/main/java/com/wootecam/festivals/domain/member/service/MemberService.java
  src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  src/main/java/com/wootecam/festivals/domain/purchase/entity/Purchase.java
  src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  src/main/java/com/wootecam/festivals/domain/ticket/controller/TicketController.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  src/main/java/com/wootecam/festivals/domain/ticket/exception/TicketErrorCode.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  src/test/java/com/wootecam/festivals/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalIdResponseTest.java
  src/test/java/com/wootecam/festivals/domain/festival/entity/FestivalTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalPublicationStatusUpdateServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/util/FestivalValidatorTest.java
  src/test/java/com/wootecam/festivals/domain/member/controller/MemberControllerTest.java
  src/test/java/com/wootecam/festivals/domain/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/controller/TicketControllerTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketStockTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketTest.java
Labels: 리팩토링

#68 feat#62/페스티벌 상세 페이지에서 티켓 종류 조회 구현
  src/docs/asciidoc/api/domain/ticket/Ticket.adoc
  src/main/java/com/wootecam/festivals/domain/ticket/controller/TicketController.java
  src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketListResponse.java
  src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketResponse.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  src/test/java/com/wootecam/festivals/domain/ticket/controller/TicketControllerTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
Labels: 기능

#71 feat#67/ Festival 고도화
  src/docs/asciidoc/api/domain/festival/Festival.adoc
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/Cursor.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalListResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/FestivalResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  src/main/java/com/wootecam/festivals/global/exception/GlobalExceptionHandler.java
  src/main/java/com/wootecam/festivals/global/utils/CustomLocalDateTimeSerializer.java
  src/main/java/com/wootecam/festivals/global/utils/DateTimeUtils.java
  src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/dto/FestivalCreateRequestTest.java
  src/test/java/com/wootecam/festivals/domain/festival/entity/FestivalTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
Labels: 기능

#70 fix#66/ 동적 스케줄링 로직 수정 및 테스트 리팩터링
  src/main/java/com/wootecam/festivals/FestivalsApplication.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerService.java
  src/main/resources/application.yml
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/resources/application.yml
Labels: 버그, 리팩토링

#69 Feat#54/체크인 로직 구현
  src/docs/asciidoc/api/domain/checkin/Checkin.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/domain/checkin/controller/CheckinController.java
  src/main/java/com/wootecam/festivals/domain/checkin/dto/CheckinIdResponse.java
  src/main/java/com/wootecam/festivals/domain/checkin/entity/Checkin.java
  src/main/java/com/wootecam/festivals/domain/checkin/exception/CheckinErrorCode.java
  src/main/java/com/wootecam/festivals/domain/checkin/repository/CheckinRepository.java
  src/main/java/com/wootecam/festivals/domain/checkin/service/CheckinService.java
  src/main/java/com/wootecam/festivals/domain/festival/entity/Festival.java
  src/main/java/com/wootecam/festivals/domain/member/entity/Member.java
  src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchaseTicketResponse.java
  src/main/java/com/wootecam/festivals/domain/purchase/entity/Purchase.java
  src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  src/main/java/com/wootecam/festivals/global/api/ApiResponse.java
  src/test/java/com/wootecam/festivals/domain/auth/service/AuthServiceTest.java
  src/test/java/com/wootecam/festivals/domain/checkin/controller/CheckinControllerTest.java
  src/test/java/com/wootecam/festivals/domain/checkin/service/CheckinServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalPublicationStatusUpdateServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalSchedulerServiceTest.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/wootecam/festivals/domain/member/service/MemberServiceTest.java
  src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/wootecam/festivals/utils/SpringBootTestConfig.java
  src/test/java/com/wootecam/festivals/utils/TestDBCleaner.java
Labels: 기능

#76 fix#73/TicketValidator 티켓 판매 시간 검증 변경
  src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketValidConstant.java
  src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketValidator.java
  src/test/java/com/wootecam/festivals/domain/checkin/service/CheckinServiceTest.java
  src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketStockTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/wootecam/festivals/domain/ticket/utils/TicketValidatorTest.java
Labels: 버그

#72 feat#63/내가 개최한 페스티벌 목록 조회
  src/docs/asciidoc/api/domain/my/my.adoc
  src/docs/asciidoc/common/organization-role.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/my/controller/MyController.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyFestivalCursor.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyFestivalRequestParams.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyFestivalResponse.java
  src/main/java/com/wootecam/festivals/domain/my/service/MyService.java
  src/main/java/com/wootecam/festivals/global/constants/GlobalConstants.java
  src/main/java/com/wootecam/festivals/global/page/CursorBasedPage.java
  src/test/java/com/wootecam/festivals/domain/my/controller/MyControllerTest.java
  src/test/java/com/wootecam/festivals/domain/my/service/MyServiceTest.java
Labels: 기능

#77 feat#61/페스티벌 참여자 목록 조회 기능 구현
  src/docs/asciidoc/api/domain/festival/FestivalParticipant.adoc
  src/main/java/com/wootecam/festivals/domain/festival/controller/FestivalParticipantController.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/PagingRequest.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/ParticipantResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/dto/ParticipantsPaginationResponse.java
  src/main/java/com/wootecam/festivals/domain/festival/exception/FestivalErrorCode.java
  src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  src/main/java/com/wootecam/festivals/domain/festival/service/FestivalParticipantService.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyFestivalRequestParams.java
  src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  src/main/java/com/wootecam/festivals/global/exception/GlobalExceptionHandler.java
  src/test/java/com/wootecam/festivals/domain/festival/controller/FestivalParticipantControllerTest.java
  src/test/java/com/wootecam/festivals/domain/festival/fixture/FestivalParticipantFixture.java
  src/test/java/com/wootecam/festivals/domain/festival/service/FestivalParticipantServiceTest.java
Labels: 기능

#78 feat#75/ 내가 구매한 특정 티켓 상세 조회 API
  src/docs/asciidoc/api/domain/my/my.adoc
  src/main/java/com/wootecam/festivals/domain/my/controller/MyController.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyPurchasedTicketResponse.java
  src/main/java/com/wootecam/festivals/domain/my/service/MyService.java
  src/main/java/com/wootecam/festivals/domain/purchase/exception/PurchaseErrorCode.java
  src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketWithoutStockResponse.java
  src/test/java/com/wootecam/festivals/domain/my/controller/MyControllerTest.java
  src/test/java/com/wootecam/festivals/domain/my/service/MyServiceTest.java
Labels: 기능

#79 feat#74/ 내가 구매한 페스티벌 목록 조회
  src/docs/asciidoc/api/domain/my/my.adoc
  src/main/java/com/wootecam/festivals/domain/my/controller/MyController.java
  src/main/java/com/wootecam/festivals/domain/my/dto/MyPurchasedFestivalResponse.java
  src/main/java/com/wootecam/festivals/domain/my/service/MyService.java
  src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchaseRepository.java
  src/test/java/com/wootecam/festivals/domain/my/controller/MyControllerTest.java
  src/test/java/com/wootecam/festivals/domain/my/service/MyServiceTest.java
Labels: 기능

#86 config#83/프론트엔드 프로젝트 구조 세팅 및 기초 페이지 레이아웃 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/ui/button/Button.css
  frontend/src/components/ui/button/Button.js
  frontend/src/components/ui/button/index.js
  frontend/src/components/ui/card/Card.css
  frontend/src/components/ui/card/Card.js
  frontend/src/components/ui/card/index.js
  frontend/src/components/ui/input/Input.css
  frontend/src/components/ui/input/Input.js
  frontend/src/components/ui/input/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/festival/FestivalDetail.js
  frontend/src/pages/festival/FestivalList.js
  frontend/src/pages/my/MyTicketList.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/src/styles/globals.css
  frontend/src/styles/tailwind.config.js
Labels: 설정

#89 feat#64/S3 이미지 업로드 기능 구현
  backend/src/main/java/com/wootecam/festivals/FestivalsApplication.java
  backend/src/main/java/com/wootecam/festivals/domain/file/controller/FileController.java
  backend/src/main/java/com/wootecam/festivals/domain/file/dto/FileResponseDto.java
  backend/src/main/java/com/wootecam/festivals/domain/file/service/FilePrefixType.java
  backend/src/main/java/com/wootecam/festivals/domain/file/service/FileService.java
  backend/src/main/java/com/wootecam/festivals/global/config/CloudConfiguration.java
  backend/src/main/java/com/wootecam/festivals/global/config/S3Config.java
  backend/src/main/java/com/wootecam/festivals/global/utils/UuidProvider.java
  backend/src/test/java/com/wootecam/festivals/domain/file/controller/FileControllerTest.java
  backend/src/test/java/com/wootecam/festivals/domain/file/service/FileServiceTest.java
  backend/src/test/resources/application.yml
Labels: 기능

#84 feat#80/결제 미리보기 화면 API 구현 및 결제 로직 기능 구현
  backend/.gitignore
  backend/src/docs/asciidoc/api/domain/purchase/purchase.adoc
  backend/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchasePreviewInfoResponse.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/PaymentService.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  backend/src/main/java/com/wootecam/festivals/domain/ticket/utils/TicketFinder.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeServiceTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
Labels: 기능

#94 config#91/DDL 정의 및 더미 데이터 생성
  backend/docker-compose.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data/ddl.sql
Labels: 설정

#98 test#92/ k6 테스트 시나리오 작성
  backend/k6/scripts/load-test.js
  backend/src/docs/asciidoc/api/domain/purchase/purchase.adoc
Labels: 기타

#100 test#92 k6 부하테스트 고도화
  backend/k6-monitoring/docker-compose.yml
  backend/k6-monitoring/scripts/load-test.js
  backend/src/main/resources/application.yml
Labels: 기타

#99 feat#85/모니터링 구축 및 도커 재설정
  backend/Dockerfile
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  backend/src/main/java/com/wootecam/festivals/global/interceptor/AuthInterceptor.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/prometheus.yml
Labels: 기능

#96 feat#93/ 구매 동시성 테스트
  backend/build.gradle
  backend/src/test/java/com/wootecam/festivals/domain/purchase/PurchaseSyncTest.java
Labels: 기능

#104 chore#103/하이버네이트 로그 및 application.yml 수정
  backend/src/main/resources/application.yml
Labels: 설정

#102 feat#95/티켓 결제 여부 확인하는 api 구현
  backend/src/docs/asciidoc/api/domain/purchase/purchase.adoc
  backend/src/main/java/com/wootecam/festivals/FestivalsApplication.java
  backend/src/main/java/com/wootecam/festivals/domain/auth/exception/AuthErrorCode.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchasableResponse.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseAuthorityCleanupScheduleService.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/service/TicketStockRollbacker.java
  backend/src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  backend/src/main/java/com/wootecam/festivals/global/auth/SessionConfig.java
  backend/src/main/java/com/wootecam/festivals/global/config/CustomMapSessionRepository.java
  backend/src/main/java/com/wootecam/festivals/global/utils/SessionUtils.java
  backend/src/main/java/com/wootecam/festivals/global/utils/TimeProvider.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data/ddl.sql
  backend/src/test/java/com/wootecam/festivals/domain/purchase/PurchaseSyncTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchasableAuthorityCleanupScheduleServiceTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeServiceTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  backend/src/test/java/com/wootecam/festivals/domain/purchase/service/TicketStockRollbackerTest.java
  backend/src/test/java/com/wootecam/festivals/utils/Fixture.java
Labels: 기능

#107 fix#106/ hibernate 정보를 액츄에이터로 나타내기 위한 의존성 추가
  backend/build.gradle
  backend/src/main/resources/application.yml
Labels: 버그, 설정

#108 config/코드 리뷰 봇 프롬프트 수정
  .github/workflows/cr.yml
Labels: CI

#105 feat#97/ 페스티벌 상세 조회, 목록 첫페이지 캐싱
  backend/build.gradle
  backend/src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  backend/src/main/java/com/wootecam/festivals/global/config/CacheConfig.java
  backend/src/test/java/com/wootecam/festivals/domain/festival/service/FestivalServiceTest.java
Labels: 기능

#114 feat#87/ 페스티벌 화면
  backend/src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.js
  frontend/src/app.css
  frontend/src/components/ProtectedRoute.js
  frontend/src/components/ui/AuthContext.js
  frontend/src/components/ui/Footer.js
  frontend/src/components/ui/Header.js
  frontend/src/components/ui/layout.js
  frontend/src/index.js
  frontend/src/pages/auth/LoginPage.js
  frontend/src/pages/festival/FestivalDetail.js
  frontend/src/pages/festival/FestivalList.js
  frontend/src/styles/globals.css
  frontend/src/styles/tailwind.config.js
  frontend/tailwind.config.js
Labels: 기능

#113 test#112/k6 스크립트 최신화 및 중복 로그인 방지 로직 추가
  backend/k6-monitoring/scripts/event-test.js
  backend/k6-monitoring/scripts/normal-test.js
  backend/src/main/java/com/wootecam/festivals/domain/auth/controller/AuthController.java
  backend/src/main/java/com/wootecam/festivals/domain/auth/exception/AuthErrorCode.java
  backend/src/main/java/com/wootecam/festivals/domain/auth/service/AuthService.java
  backend/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/wootecam/festivals/global/utils/AuthenticationUtils.java
  backend/src/main/java/com/wootecam/festivals/global/utils/SessionUtils.java
  backend/src/test/java/com/wootecam/festivals/domain/auth/service/AuthServiceTest.java
Labels: 버그, 기타

#118 hotfix#117/ 내가 참여한 페스티벌 목록 조회 id, starttime null 체킹
  backend/src/main/java/com/wootecam/festivals/domain/my/service/MyService.java
  backend/src/test/java/com/wootecam/festivals/domain/my/service/MyServiceTest.java
Labels: 버그

#122 fix#121/티켓 동시 구매 중 중복 구매하는 버그 픽스
  backend/k6-monitoring/scripts/event-test.js
Labels: 버그

#125 refactor#115/spring 성능 개선
  backend/api-server/src/main/java/com/wootecam/festivals/FestivalsApplication.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/checkin/repository/CheckinRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/festival/repository/FestivalRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/entity/Purchase.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/auth/Authentication.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/interceptor/AuthInterceptor.java
  backend/api-server/src/main/resources/application.yml
  backend/api-server/src/main/resources/data/ddl.sql
  backend/api-server/src/test/java/com/wootecam/festivals/domain/auth/service/AuthServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/member/controller/MemberControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/interceptor/AuthInterceptorTest.java
Labels: 리팩토링

#130 feat#124/티켓 재고 엔티티 변경
  backend/api-server/Dockerfile
  backend/api-server/docker-compose.yml
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchasableResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/dto/PurchasePreviewInfoResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseAuthorityCleanupScheduleService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/TicketStockRollbacker.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/dto/TicketResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/entity/Ticket.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketStock.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/exception/TicketErrorCode.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockJdbcRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  backend/api-server/src/main/resources/application.yml
  backend/api-server/src/main/resources/data/ddl.sql
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/PurchaseSyncTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchasableAuthorityCleanupScheduleServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/TicketStockRollbackerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/controller/TicketControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketStockTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/entity/TicketTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/repository/TicketStockJdbcRepositoryTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/service/TicketServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/utils/Fixture.java
Labels: 기능, 리팩토링

#131 Feat#119/ Redis Dao 구현
  backend/build.gradle
  backend/queue-server/build.gradle
  backend/queue-server/src/main/java/com/wootecam/PurchasedMemberRepository.java
  backend/queue-server/src/main/java/com/wootecam/QueueApplication.java
  backend/queue-server/src/main/java/com/wootecam/RedisConfig.java
  backend/queue-server/src/main/java/com/wootecam/RedisRepository.java
  backend/queue-server/src/main/java/com/wootecam/SimpleTest.java
  backend/queue-server/src/main/java/com/wootecam/TicketStockRepository.java
  backend/queue-server/src/main/java/com/wootecam/WaitingRepository.java
  backend/queue-server/src/main/resources/application.yml
  backend/queue-server/src/test/java/com/wootecam/EmbeddedRedisConfig.java
  backend/queue-server/src/test/java/com/wootecam/PurchasedMemberRepositoryTest.java
  backend/queue-server/src/test/java/com/wootecam/QueueApplicationTest.java
  backend/queue-server/src/test/java/com/wootecam/SimpleTestTest.java
  backend/queue-server/src/test/java/com/wootecam/TicketStockRepositoryTest.java
  backend/queue-server/src/test/java/com/wootecam/WaitingRepositoryTest.java
  backend/queue-server/src/test/resources/application.yml
Labels: 기능

#127 feat#101/mysql 비동기 배치처리 작성
  backend/api-server/src/docs/asciidoc/api/domain/purchase/purchase.adoc
  backend/api-server/src/main/java/com/wootecam/festivals/domain/checkin/entity/Checkin.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/excpetion/PaymentErrorCode.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/dto/PaymentIdResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/dto/PaymentStatusResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/dto/CachedTicketInfo.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketCacheService.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/config/CacheConfig.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/CustomQueue.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/InMemoryQueue.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/dto/PurchaseData.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/exception/QueueFullException.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/exception/QueueOperationException.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/service/QueueService.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/payment/service/PaymentServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/service/TicketCacheServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/queue/InMemoryQueueTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/queue/service/QueueServiceIntegrationTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/queue/service/QueueServiceTest.java
Labels: 기능

#135 hotfix#134: 한 명의 유저가 티켓을 여러개 점유하던 버그 수정
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/exception/TicketErrorCode.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockRepository.java
  backend/api-server/src/main/resources/data/ddl.sql
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
Labels: 버그

#133 feat#132/frontend 화면 구성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ProtectedRoute.js
  frontend/src/components/contexts/AuthContext.js
  frontend/src/components/ui/AuthContext.js
  frontend/src/components/ui/Footer.js
  frontend/src/components/ui/Header.js
  frontend/src/components/ui/input/Input.js
  frontend/src/components/ui/layout.js
  frontend/src/components/ui/textarea/Textarea.css
  frontend/src/components/ui/textarea/Textarea.js
  frontend/src/components/ui/textarea/index.js
  frontend/src/pages/admin/FestivalManagement.js
  frontend/src/pages/auth/LoginPage.js
  frontend/src/pages/auth/SignupPage.js
  frontend/src/pages/festival/CreateFestivalPage.js
  frontend/src/pages/festival/FestivalDetail.js
  frontend/src/pages/festival/FestivalList.js
  frontend/src/pages/festival/TicketPurchasePage.js
  frontend/src/pages/my/HostedFestival.js
  frontend/src/pages/my/MyPage.js
  frontend/src/pages/my/MyTicketList.js
  frontend/src/pages/my/PurchasedTickets.js
  frontend/src/utils/apiClient.js
Labels: 기능

#138 feat#137/ 현재 구매중인 유저 RedisRepository 구현
  backend/build.gradle
  backend/core/src/main/java/com/wootecam/CurrentlyPayingMemberRepository.java
  backend/core/src/main/java/com/wootecam/PurchasedMemberRepository.java
  backend/core/src/main/java/com/wootecam/QueueApplication.java
  backend/core/src/main/java/com/wootecam/RedisConfig.java
  backend/core/src/main/java/com/wootecam/RedisRepository.java
  backend/core/src/main/java/com/wootecam/TicketStockRepository.java
  backend/core/src/main/java/com/wootecam/WaitingRepository.java
  backend/core/src/main/resources/application.yml
  backend/core/src/test/java/com/wootecam/CurrentlyPayingMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/EmbeddedRedisConfig.java
  backend/core/src/test/java/com/wootecam/PurchasedMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/QueueApplicationTest.java
  backend/core/src/test/java/com/wootecam/TicketStockRepositoryTest.java
  backend/core/src/test/java/com/wootecam/WaitingRepositoryTest.java
  backend/core/src/test/resources/application.yml
  backend/queue-server/build.gradle
  backend/queue-server/src/main/java/com/wootecam/PurchasedMemberRepository.java
  backend/queue-server/src/main/java/com/wootecam/SimpleTest.java
  backend/queue-server/src/main/java/com/wootecam/global/config/RedisConfig.java
  backend/queue-server/src/test/java/com/wootecam/SimpleTestTest.java
  backend/settings.gradle
Labels: 기능

#128 feat#123/api,응답 코드,실행 시간 로깅 필터 구현
  backend/api-server/src/docs/asciidoc/api/domain/purchase/purchase.adoc
  backend/api-server/src/main/resources/application.yml
  backend/api-server/src/test/java/com/wootecam/festivals/domain/auth/service/AuthServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/interceptor/AuthInterceptorTest.java
  backend/build.gradle
  backend/core/src/main/java/com/wootecam/QueueApplication.java
  backend/core/src/main/java/com/wootecam/RedisConfig.java
  backend/core/src/main/java/com/wootecam/RedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/CurrentlyPayingMemberRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchasedMemberRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/RedisConfig.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/RedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/TicketStockRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/purchase/repository/WaitingRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/global/config/CustomMapSessionRepository.java
  backend/core/src/main/java/com/wootecam/festivals/global/config/RedisSessionConfig.java
  backend/core/src/main/java/com/wootecam/festivals/global/interceptor/AuthInterceptor.java
  backend/core/src/main/java/com/wootecam/festivals/global/log/LoggingFilter.java
  backend/core/src/test/java/com/wootecam/CurrentlyPayingMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/PurchasedMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/TicketStockRepositoryTest.java
  backend/core/src/test/java/com/wootecam/WaitingRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/CurrentlyPayingMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/EmbeddedRedisConfig.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/PurchasedMemberRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/TicketStockRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/WaitingRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/global/interceptor/AuthInterceptorTest.java
Labels: 기능

#144 feat#139/프론트엔드 고도화
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/service/PaymentService.java
  backend/core/src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/contexts/AuthContext.js
  frontend/src/components/ui/Header.js
  frontend/src/pages/admin/FestivalInfo.js
  frontend/src/pages/admin/FestivalManagement.js
  frontend/src/pages/admin/PurchasersList.js
  frontend/src/pages/admin/TicketManagement.js
  frontend/src/pages/festival/FestivalDetail.js
  frontend/src/pages/festival/PaymentProcessPage.js
  frontend/src/pages/festival/TicketPurchasePage.js
  frontend/src/pages/my/MyPage.js
  frontend/src/pages/my/PurchasedTickets.js
Labels: 기능

#145 feat#136/mysql 비동기 고도화
  backend/api-server/build.gradle
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/dto/CachedTicketInfo.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketCacheService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/config/CacheConfig.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/InMemoryQueue.java
  backend/api-server/src/main/java/com/wootecam/festivals/global/queue/service/QueueService.java
  backend/api-server/src/main/resources/logback-spring.xml
  backend/api-server/src/test/java/com/wootecam/festivals/domain/festival/stub/FestivalStub.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/payment/service/PaymentServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/service/TicketCacheServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/queue/service/QueueServiceIntegrationTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/global/queue/service/QueueServiceTest.java
Labels: 기능

#149 feat: 빌드시 에러발생 해결을 위한 의존성 추가
  frontend/package-lock.json
  frontend/package.json
Labels: 기능

#153 feat#150/ 프론트엔드 페이지 qr 추가
  _redirects
  backend/api-server/src/main/java/com/wootecam/festivals/domain/my/dto/MyPurchasedTicketResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchaseRepository.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/my/controller/MyControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/service/TicketCacheServiceTest.java
  backend/build.gradle
  backend/core/src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  backend/k6-monitoring/scripts/main.js
  frontend/_redirects
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/logo.svg
  frontend/src/App.js
  frontend/src/components/ui/Header.js
  frontend/src/pages/admin/FestivalManagement.js
  frontend/src/pages/admin/PurchasersList.js
  frontend/src/pages/auth/LoginPage.js
  frontend/src/pages/auth/SignupPage.js
  frontend/src/pages/festival/FestivalList.js
  frontend/src/pages/festival/TicketPurchasePage.js
  frontend/src/pages/my/PurchasedTickets.js
  frontend/src/utils/apiClient.js
Labels: 기능

#156 hotfix#155/ 프론트엔드 회원가입 url 오타 수정
  frontend/src/pages/auth/SignupPage.js
Labels: 버그

#158 hotfix#157api 오류 리다이렉트 페이지 주소 변경
  frontend/src/utils/apiClient.js
  frontend/src/utils/waitClient.js
Labels: 버그

#163 feat#159/대기열 로직에 티켓 판매 시각 검증 및 티켓팅 진행할 티켓 관리 로직 추가
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketScheduleService.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/ticket/service/TicketScheduleServiceTest.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/entity/TicketInfo.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/repository/CurrentTicketWaitRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockCountRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockRedisRepository.java
  backend/k6-monitoring/scripts/payment-status-polling-test.js
  backend/k6-monitoring/scripts/wait-event-test.js
  backend/queue-server/src/main/java/com/wootecam/festivals/domain/wait/PassOrder.java
  backend/queue-server/src/main/java/com/wootecam/festivals/domain/wait/exception/WaitErrorCode.java
  backend/queue-server/src/main/java/com/wootecam/festivals/domain/wait/repository/PassOrderRedisRepository.java
  backend/queue-server/src/main/java/com/wootecam/festivals/domain/wait/service/WaitOrderService.java
  backend/queue-server/src/test/java/com/wootecam/festivals/domain/wait/PassOrderTest.java
  backend/queue-server/src/test/java/com/wootecam/festivals/domain/wait/service/WaitOrderServiceTest.java
Labels: 기능

#164 hotfix#160/티켓 대기번호 전역변수로 관리
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/pages/festival/TicketQueuePage.js
  frontend/src/utils/atoms.js
Labels: 기능

#165 feat#161/보상 transaction
  backend/api-server/src/docs/asciidoc/api/domain/purchase/purchase.adoc
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/dto/PaymentInfo.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/payment/service/PaymentService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/controller/PurchaseController.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/CompensationService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseFacadeService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/service/PurchaseService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketScheduleService.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/payment/service/PaymentServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/controller/PurchaseControllerTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/CompensationServiceTest.java
  backend/api-server/src/test/java/com/wootecam/festivals/domain/purchase/service/PurchaseServiceTest.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/repository/PurchaseSessionRedisRepository.java
  backend/core/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockCountRedisRepository.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/PurchaseSessionRedisRepositoryTest.java
  backend/core/src/test/java/com/wootecam/festivals/domain/purchase/repository/TicketStockRepositoryTest.java
  backend/queue-server/src/main/java/com/wootecam/festivals/domain/wait/service/WaitOrderService.java
  backend/queue-server/src/test/java/com/wootecam/festivals/domain/wait/service/WaitOrderServiceTest.java
Labels: 기능

#166 hotfix#162/front festival List 페이지 버그 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/festival/FestivalList.js
Labels: 버그

#168 feat#167/ 웹 프론트엔드 cors 설정
  backend/core/src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
  frontend/src/pages/festival/FestivalList.js
Labels: 기능

#170 fix#169/파싱 에러 수정
  backend/api-server/src/main/java/com/wootecam/festivals/domain/my/dto/MyPurchasedTicketResponse.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/purchase/repository/PurchaseRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  frontend/src/pages/my/PurchasedTickets.js
Labels: 버그

#173 Hotfix#/캐시로 인해 페이지가 나오지 않던 문제 수정, 배치업데이트 버그 수정
  backend/api-server/src/main/java/com/wootecam/festivals/domain/festival/service/FestivalService.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/repository/TicketStockJdbcRepository.java
  backend/api-server/src/main/java/com/wootecam/festivals/domain/ticket/service/TicketService.java
  frontend/src/pages/admin/TicketManagement.js
Labels: 버그
